// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    helloworld
    (
        init => init
        upgrade => upgrade
        sayHello => say_hello
        calculate => add
        sayHelloToNextCaller => say_hello_to_next_caller
        sayHelloToOffChain => say_hello_to_off_chain
        sayHelloOnlyWhenPaid => say_hello_only_when_paid
        payUser => pay_user
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
